pipeline {
    agent any
    stages {
        stage('Build Backend') {
            steps {
                shell 'mvn clean package -DskipTests=true'
            }
        }
        stage('Sonnar Analysis') {
             environment {
                    scannerHome = tool 'SONAR_SCANNER'
               }
                    steps {
                        shell "${scannerHome}/bin/sonar-scanner -e "
                    }
                }
    }
}