version: '3.5'

services:
  postgres-apartamento:
    container_name: 'postgres-apartamento'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bdapartamento
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-network-apartamento

  rabbitmq:
    container_name: 'rabbitmq_apartamento'
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata/:/var/lib/rabbitmq/
    networks:
      - postgres-network-apartamento

  # rabbitmq
  # usuario: guest
  # senha: guest

  pgadmin-compose:
    container_name: 'pgadmin_apartamento'
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16544:80"
    networks:
      - postgres-network-apartamento

networks:
  postgres-network-apartamento:
    driver: bridge
  rabbitmq_network-apartamento:
    driver: bridge

volumes:
  pgdata:
  rabbitmqdata:
